# Generated by Django 4.1.4 on 2023-02-10 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatData',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_chat', models.CharField(max_length=100)),
                ('chat_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chat_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommentData',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_cont', models.CharField(max_length=1024)),
                ('comment_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'comment_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('contents', models.CharField(max_length=1024)),
                ('category', models.CharField(max_length=45)),
                ('receive_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=45)),
                ('contents_data', models.TextField()),
                ('post_time', models.DateTimeField()),
                ('num_of_open', models.IntegerField()),
                ('num_of_recommend', models.IntegerField()),
                ('post_title', models.CharField(blank=True, max_length=1024, null=True)),
                ('post_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'post_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamApplyLog',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'team_apply_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('team_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('introduction', models.CharField(blank=True, max_length=1024, null=True)),
                ('team_make_time', models.DateTimeField()),
                ('team_category', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'team_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=50)),
                ('post_contents', models.TextField()),
                ('post_time', models.DateTimeField()),
                ('post_type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'team_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamUserData',
            fields=[
                ('pr_key', models.AutoField(primary_key=True, serialize=False)),
                ('is_admin', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'team_user_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_pass', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('user_admin', models.CharField(blank=True, max_length=1, null=True)),
                ('login_state', models.CharField(blank=True, max_length=1, null=True)),
                ('user_email', models.CharField(max_length=512)),
                ('user_comment', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'user_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='profile_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_photo', models.ImageField(upload_to='media/profile')),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='team_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_post_id', models.CharField(max_length=100)),
                ('files', models.FileField(upload_to='TestFolder')),
            ],
        ),
        migrations.CreateModel(
            name='WebBackProfilePhoto',
            fields=[
                ('user_photo', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web_back.userdata')),
            ],
            options={
                'db_table': 'web_back_profile_photo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebBackTeamFile',
            fields=[
                ('the_post_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web_back.teampost')),
                ('files', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'web_back_team_file',
                'managed': False,
            },
        ),
    ]
