# Generated by Django 4.1.4 on 2023-03-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItemLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user_item_log',
                'managed': False,
            },
        ),
    ]
